name: contract-test

on:
  pull_request:
    types: [opened, synchronize]

env:
  PACT_BROKER_BASE_URL: ${{secrets.PACT_BROKER_BASE_URL}}
  PACT_BROKER_TOKEN: ${{secrets.PACT_BROKER_TOKEN}}
  PACTICIPANT: MartinsMessageProvider
  PACTICIPANT_VERSION: ${{ github.event.pull_request.head.sha }}
  DEPLOY_TARGET: ${{ github.base_ref }}
  GIT_BRANCH: master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
      - name: Can i deploy?
        run: >
          yarn pact-broker can-i-deploy
          --pacticipant $PACTICIPANT
          --version $PACTICIPANT_VERSION
          --to $DEPLOY_TARGET
          --retry-while-unknown 3 
          --retry-interval 30
          --broker-base-url $PACT_BROKER_BASE_URL
          --broker-token $PACT_BROKER_TOKEN
